---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: astro version
    register: astro_test_output
  - name: astro version
    debug:
      msg: '{{ astro_test_output.stdout }}'
