---
- name: Testing andrewrothstein.astro
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'astro version'
      ansible.builtin.command: astro version
      changed_when: false
      register: astro_test_output
    - name: Output from 'astro version'
      ansible.builtin.debug:
        msg: '{{ astro_test_output.stdout }}'
