---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install at {{ astro_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ astro_install_dir }}'
  changed_when: false
  register: astro_binary
- name: Downloading and installing astro
  when: not astro_binary.stat.exists
  block:
    - name: Download from {{ astro_url }} to {{ astro_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ astro_url }}'
        dest: '{{ astro_tmp_archive }}'
        mode: '644'
        checksum: '{{ astro_checksum }}'
    - name: Mkdir {{ astro_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ astro_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchive {{ astro_tmp_archive }} to {{ astro_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ astro_tmp_archive }}'
        dest: '{{ astro_install_dir }}'
        creates: '{{ astro_install_exe }}'
  always:
    - name: Rm -f {{ astro_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ astro_tmp_archive }}'
        state: absent
- name: Link {{ astro_link }} to {{ astro_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ astro_install_exe }}'
    dest: '{{ astro_link }}'
    state: link
