---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install at {{ astro_install_dir }}
  become: true
  stat:
    path: '{{ astro_install_dir }}'
  changed_when: False
  register: astro_binary
- when: not astro_binary.stat.exists
  block:
    - name: download from {{ astro_url }} to {{ astro_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ astro_url }}'
        dest: '{{ astro_tmp_archive }}'
        mode: 0644
        checksum: '{{ astro_checksum }}'
    - name: mkdir {{ astro_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ astro_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ astro_tmp_archive }} to {{ astro_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ astro_tmp_archive }}'
        dest: '{{ astro_install_dir }}'
        creates: '{{ astro_install_exe }}'
  always:
    - name: rm {{ astro_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ astro_tmp_archive }}'
        state: absent
- name: link {{ astro_link }} to {{ astro_install_exe }}
  become: true
  become_user: root
  file:
    src: '{{ astro_install_exe }}'
    dest: '{{ astro_link }}'
    state: link
